# Generated by Django 5.1.7 on 2025-03-28 13:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_questionvote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionvote',
            unique_together={('user', 'question', 'vote_type')},
        ),
    ]
