# Generated by Django 5.1.7 on 2025-03-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_vote_delete_questionvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.TextField(blank=True, default=''),
        ),
    ]
