# Generated by Django 5.1.7 on 2025-03-28 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_answer_question_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question_id',
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Post.question'),
        ),
    ]
