# Generated by Django 5.1.7 on 2025-03-28 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0009_remove_answer_question_id_alter_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_votes', to='Post.answer'),
        ),
    ]
