# Generated by Django 5.1.7 on 2025-03-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
