# Generated by Django 5.1.7 on 2025-03-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_customuser_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='pictire',
            new_name='avatar',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='downvotes',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='upvotes',
            field=models.TextField(default=0),
        ),
    ]
