# Generated by Django 5.1.7 on 2025-03-28 09:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
        ('User', '0002_remove_customuser_avatar_customuser_avatar_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bronze_badges',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gold_badges',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='member_since',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='silver_badges',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='top_tags',
            field=models.ManyToManyField(blank=True, related_name='users', to='Post.tag'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reputation',
            field=models.IntegerField(default=1),
        ),
    ]
