# Generated by Django 5.1.7 on 2025-03-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_customuser_bronze_badges_customuser_gold_badges_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='avatar_path',
            new_name='avatar_url',
        ),
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
    ]
