# Generated by Django 5.1.7 on 2025-03-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_rename_pictire_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='upvotes',
        ),
    ]
