# Generated by Django 5.1.7 on 2025-03-26 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_remove_customuser_downvotes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_seen',
        ),
    ]
