# Generated by Django 5.1.7 on 2025-03-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_remove_customuser_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
