# Generated by Django 5.1.7 on 2025-03-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='media/8D92351E-F4D2-4656-A774-5CDCE818D383.png', null=True, upload_to='pictures/'),
        ),
    ]
