# Generated by Django 5.1.7 on 2025-03-29 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_rename_display_name_customuser_displayname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('question_upvote', 'Question Upvote'), ('answer_upvote', 'Answer Upvote'), ('answer_accepted', 'Answer Accepted'), ('answer_downvote', 'Answer Downvote'), ('question_downvote', 'Question Downvote')], default='!no data!', max_length=20)),
                ('change', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_changes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
