# Generated by Django 5.1.7 on 2025-03-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_reputation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='bio',
            new_name='about',
        ),
    ]
